/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArmoryRouteImport } from './routes/armory'
import { Route as CrewsRouteImport } from './routes/crews'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as GamesRouteImport } from './routes/games'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SeasonRouteImport } from './routes/season'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SocialRouteImport } from './routes/social'
import { Route as StudyRouteImport } from './routes/study'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmoryRoute = ArmoryRouteImport.update({
  id: '/armory',
  path: '/armory',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewsRoute = CrewsRouteImport.update({
  id: '/crews',
  path: '/crews',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonRoute = SeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/armory': typeof ArmoryRoute
  '/crews': typeof CrewsRoute
  '/discover': typeof DiscoverRoute
  '/friends': typeof FriendsRoute
  '/games': typeof GamesRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/season': typeof SeasonRoute
  '/shop': typeof ShopRoute
  '/social': typeof SocialRoute
  '/study': typeof StudyRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/armory': typeof ArmoryRoute
  '/crews': typeof CrewsRoute
  '/discover': typeof DiscoverRoute
  '/friends': typeof FriendsRoute
  '/games': typeof GamesRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/season': typeof SeasonRoute
  '/shop': typeof ShopRoute
  '/social': typeof SocialRoute
  '/study': typeof StudyRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/armory': typeof ArmoryRoute
  '/crews': typeof CrewsRoute
  '/discover': typeof DiscoverRoute
  '/friends': typeof FriendsRoute
  '/games': typeof GamesRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/season': typeof SeasonRoute
  '/shop': typeof ShopRoute
  '/social': typeof SocialRoute
  '/study': typeof StudyRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/armory'
    | '/crews'
    | '/discover'
    | '/friends'
    | '/games'
    | '/messages'
    | '/profile'
    | '/season'
    | '/shop'
    | '/social'
    | '/study'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/armory'
    | '/crews'
    | '/discover'
    | '/friends'
    | '/games'
    | '/messages'
    | '/profile'
    | '/season'
    | '/shop'
    | '/social'
    | '/study'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/armory'
    | '/crews'
    | '/discover'
    | '/friends'
    | '/games'
    | '/messages'
    | '/profile'
    | '/season'
    | '/shop'
    | '/social'
    | '/study'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArmoryRoute: typeof ArmoryRoute
  CrewsRoute: typeof CrewsRoute
  DiscoverRoute: typeof DiscoverRoute
  FriendsRoute: typeof FriendsRoute
  GamesRoute: typeof GamesRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  SeasonRoute: typeof SeasonRoute
  ShopRoute: typeof ShopRoute
  SocialRoute: typeof SocialRoute
  StudyRoute: typeof StudyRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armory': {
      id: '/armory'
      path: '/armory'
      fullPath: '/armory'
      preLoaderRoute: typeof ArmoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crews': {
      id: '/crews'
      path: '/crews'
      fullPath: '/crews'
      preLoaderRoute: typeof CrewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season': {
      id: '/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof SeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArmoryRoute: ArmoryRoute,
  CrewsRoute: CrewsRoute,
  DiscoverRoute: DiscoverRoute,
  FriendsRoute: FriendsRoute,
  GamesRoute: GamesRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  SeasonRoute: SeasonRoute,
  ShopRoute: ShopRoute,
  SocialRoute: SocialRoute,
  StudyRoute: StudyRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
